### ISSUE TITLE
Add Notification Seekbar Feature

### ISSUE THREAD

**Issue by shounak-dev** [shounak-dev/My-Music#14]

**Comment by vishal2376** [comment]
I would like to work on this issue

**Comment by shounak-dev** [comment]
Sure...

**Comment by vishal2376** [comment]
Hey, there is already a seekbar in the notification

**Comment by shounak-dev** [comment]
Yes....but if we swipe the seekbar from notification,it is not working.

**Comment by vishal2376** [comment]
its working on my mobile

**Comment by vishal2376** [comment]
> Yes....but if we swipe the seekbar from notification,it is not working.

This feature is only available for android version >=Q.

**Comment by shounak-dev** [comment]
Ok
