### ISSUE TITLE
Upgrade the Seekbar

### ISSUE THREAD

**Issue by shounak-dev** [shounak-dev/My-Music#2]

**Comment by Fazil29** [comment]
Can you please elaborate the issue.

**Comment by shounak-dev** [comment]
If we play any song then we see that the seekbar is not properly visible to the user.Can you fix it?

**Comment by rishuyadav** [comment]
Heyy @shounak-dev i would like to take up the issue but am having some issues building the project,
there are some strings which are not declared and other issues can u please look into it and help
![image](https://user-images.githubusercontent.com/72988817/198314326-d95ab1ee-1e41-44b6-a7ac-95af2bc7b7d8.png)

**Comment by shounak-dev** [comment]
Now the problem is solved....please check @rishuyadav

**Comment by rishuyadav** [comment]
> If we play any song then we see that the seekbar is not properly visible to the user.Can you fix it?

But the seekbar is clearly visible to me , i didn't understand whats needed to be fixed can you please elaborate with images and more info

**Comment by shounak-dev** [comment]
I want to increase the thumb size of the seekbar so that it can visible to all user properly.
