### ISSUE TITLE
Fix Favourite Issue...

### ISSUE THREAD

**Issue by shounak-dev** [shounak-dev/My-Music#4]
favourite feature not working properly......

**Comment by vishal2376** [comment]
can you elaborate?

I would like to fix this issue.

**Comment by shounak-dev** [comment]
In the first time when we add a song into favourites it works successful, but when we exit from the app then reenter and see the favourites tab, we see that no song is there.....all song is cleared from favourites tab.

**Comment by vishal2376** [comment]
Did you store the favorite song list data on the device(storage)?

**Comment by shounak-dev** [comment]
No,not in the device(storage).....just in the app's favourites list

**Comment by vishal2376** [comment]
ok

**Comment by vishal2376** [comment]
done

**Comment by shounak-dev** [comment]
Ok
