### ISSUE TITLE
Fixing Architecture of the project

### ISSUE THREAD

**Issue by utkarsh006** [shounak-dev/My-Music#55]
- Fixing Architecture as per the [standard guidelines](https://developer.android.com/topic/architecture)
- Dividing the app's data into Data, Domain, and UI Layers.
- This is done so that, future developers may contribute easily to this project, in case the codebase becomes large, and feature handling becomes easier through these layers.
- Do assign me the issue under Hacktoberfest.

**Comment by utkarsh006** [comment]
@shounak-dev Can you have a look at this?

**Comment by shounak-dev** [comment]
Go ahead...
