### ISSUE TITLE
Upgrade Theme of the App...

### ISSUE THREAD

**Issue by shounak-dev** [shounak-dev/My-Music#7]

**Comment by RockingRishav** [comment]
Could you please tell in what way to upgrade the theme like do we just only have to make changes in themes.xml or something else ?

**Comment by shounak-dev** [comment]
Yes....just make some custom themes in themes.xml and make changes in settings tab that user can control theme from settings tab.

**Comment by shounak-dev** [comment]
Any Update?

**Comment by AdityaKumdale** [comment]
Hello there can I contribute to this project for hactoberfest 2023

**Comment by shounak-dev** [comment]
@AdityaKumdale ofcourse....

**Comment by AdityaKumdale** [comment]
Thanks,will start working on this app from tomorrow.

**Comment by AdityaKumdale** [comment]
Please check the pull request
